/**
 * This file was generated by kysely-codegen.
 * Manual edits: removed knex migration tables, tightened primary-key nullability.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Continents {
  code: string;
  name: string | null;
}

export interface Countries {
  alpha_3: string | null;
  capital: string | null;
  code: string;
  continent_code: string | null;
  currency: string | null;
  name: string | null;
  phone: number | null;
  symbol: string | null;
}

export interface Persons {
  country_code: string | null;
  first_name: string | null;
  id: Generated<number>;
  last_name: string | null;
}

export interface DB {
  continents: Continents;
  countries: Countries;
  persons: Persons;
}
